import { lazy } from 'react';
import Head from 'next/head';

import styles from '@/styles/Home.module.css';

let RemoteTitle: any = ()=>null;
if (process.browser) {
   RemoteTitle = lazy(() => {
      return import('energyservicereact/energyservicereact');
    }
  );
}

export default function Home() {
  return (
    <>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Dashboard</h1>
        
      </main>
    </>
  )
}
