import { lazy, Suspense } from 'react';
import Head from 'next/head';

import Spinner from '@/components/spinner';

import styles from '@/styles/Home.module.css';

// let RemoteServiceReactHome: any = ()=>null;
// if (process.browser) {
//   RemoteServiceReactHome = lazy(() => {
//     return import('checkout/title');
//   });
//   console.log("czxv", import('checkout/title'));
// }
import('checkout/checkout').then((mod) => {
  console.log("mod", mod);
});

const Home = () => {
  return (
    <>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Dashboard</h1>
        {/* <Suspense fallback={<Spinner />}>
          <RemoteServiceReactHome />
        </Suspense> */}
      </main>
    </>
  )
}

export default Home;
